# Generated by Django 4.1.3 on 2022-11-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibroker', '0002_sample_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/cases'),
        ),
    ]
