# Generated by Django 4.1.3 on 2022-11-12 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apibroker', '0004_alter_sample_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_key', models.CharField(default='', max_length=100, unique=True)),
                ('case_number', models.CharField(default='', max_length=100, unique=True)),
                ('plate_number', models.CharField(default='', max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('case_file', models.FileField(blank=True, null=True, upload_to='cases')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
