# Generated by Django 4.1.3 on 2022-11-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibroker', '0005_case_delete_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='customer_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='plate_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
