# Generated by Django 4.1.3 on 2022-11-23 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibroker', '0007_alter_case_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_file',
            field=models.FileField(blank=True, null=True, upload_to='cases', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'json'])]),
        ),
    ]
