# Generated by Django 4.1.3 on 2022-11-28 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apibroker', '0007_alter_case_case_file_alter_case_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='cases', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'json'])])),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='apibroker.case', verbose_name='Anexos')),
            ],
        ),
    ]
