# Generated by Django 4.1.3 on 2022-11-30 15:47

import apps.apibroker.file_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibroker', '0008_fileattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='preshared_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_file',
            field=models.FileField(blank=True, null=True, upload_to='cases', validators=[apps.apibroker.file_validator.FileValidator(content_types=('application/xml', 'application/json', 'text/xml'), max_size=102400)]),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='cases'),
        ),
    ]
