# Generated by Django 4.1.4 on 2022-12-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibroker', '0011_alter_fileattachment_file_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_file',
        ),
        migrations.DeleteModel(
            name='FileAttachment',
        ),
    ]
