# Generated by Django 4.1.4 on 2022-12-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apibroker', '0012_remove_case_case_file_delete_fileattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='UserCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(default='', max_length=100)),
                ('customer_key', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
