# Generated by Django 4.1.4 on 2022-12-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibroker', '0013_case_client_key_usercase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='customer_key',
            new_name='operator_id',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='client_key',
            new_name='origin_id',
        ),
        migrations.RenameField(
            model_name='usercase',
            old_name='customer_key',
            new_name='operator_id',
        ),
        migrations.RenameField(
            model_name='usercase',
            old_name='client_key',
            new_name='origin_id',
        ),
        migrations.RemoveField(
            model_name='case',
            name='preshared_key',
        ),
        migrations.AddField(
            model_name='case',
            name='ext_reference_nr',
            field=models.CharField(default='', max_length=100),
        ),
    ]
