# Generated by Django 4.1.4 on 2022-12-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibroker', '0015_rename_case_caseinstancemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinstancemanager',
            name='customer_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usercase',
            name='customer_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
