# Generated by Django 4.1.4 on 2022-12-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibroker', '0018_rename_usercase_dmsbsmsinstancemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmsbsmsinstancemanager',
            name='operatorId',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
