version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - atlas_backend-network
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command:
            - /bin/sh
            - -c
            - |
              celery -A main worker -l INFO &
              gunicorn main.wsgi:application --bind 0.0.0.0:8001
        volumes:
            - static_volume:/home/api-broker/web/staticfiles/
            - media_volume:/home/api-broker/web/media/
        expose:
            - 8001
        env_file:
            - ./.env.prod
        networks:
            - atlas_backend-network
        depends_on:
            - db
    db:
        image: postgres:14.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        env_file:
            - ./.env.db.prod
        networks:
            - atlas_backend-network

networks:
    atlas_backend-network:
        external: true

volumes:
    postgres_data:
    static_volume:
    media_volume:
