# Generated by Django 4.1.4 on 2022-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (9, 'User'), (19, 'Calculation Service'), (29, 'DMS'), (39, 'BSMS')], default=9),
        ),
    ]
