# Generated by Django 4.1.4 on 2022-12-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ipAddress',
            field=models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='IPAddress'),
        ),
    ]
