# Generated by Django 4.1.4 on 2022-12-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ipAddress',
        ),
    ]
